// ==UserScript==
// @name         Toloka Upload Assistant
// @version      1.5.6
// @description  Populate Toloka release form from meta.json generated by Upload Assistant (https://github.com/Audionut/Upload-Assistant). Thanks to andriyo98 for release_toloka1.sh, his script, and the idea.
// @match        https://toloka.to/release.php*
// @grant        none
// @updateURL    https://raw.githubusercontent.com/maksii/utp-script/main/toloka/toloka-fill-form.user.js
// @downloadURL  https://raw.githubusercontent.com/maksii/utp-script/main/toloka/toloka-fill-form.user.js
// ==/UserScript==

(function () {
    'use strict';

    const TMDB_STORAGE_KEY = 'toloka_fill_tmdb_apikey';

    function getStoredTmdbKey() {
        try {
            return localStorage.getItem(TMDB_STORAGE_KEY) || '';
        } catch (e) {
            return '';
        }
    }

    function setStoredTmdbKey(key) {
        try {
            if (key) localStorage.setItem(TMDB_STORAGE_KEY, key);
            else localStorage.removeItem(TMDB_STORAGE_KEY);
        } catch (e) { }
    }

    // ——— Country names: English → Ukrainian (aligned with release_toloka1.sh). Major film/TV producers.
    const COUNTRY_UA = {
        'United States': 'США', 'United States of America': 'США', 'USA': 'США',
        'United Kingdom': 'Велика Британія', 'Great Britain': 'Велика Британія', 'UK': 'Велика Британія',
        'Canada': 'Канада', 'France': 'Франція',
        'Germany': 'Німеччина', 'Japan': 'Японія',
        'South Korea': 'Південна Корея', 'Korea, Republic of': 'Південна Корея', 'Republic of Korea': 'Південна Корея',
        'North Korea': 'Північна Корея', "Korea, Democratic People's Republic of": 'Північна Корея',
        'China': 'Китай', "China, People's Republic of": 'Китай',
        'India': 'Індія', 'Italy': 'Італія', 'Spain': 'Іспанія',
        'Russia': 'Росія', 'Russian Federation': 'Росія', 'Ukraine': 'Україна',
        'Australia': 'Австралія', 'Brazil': 'Бразилія', 'Mexico': 'Мексика', 'Poland': 'Польща',
        'Netherlands': 'Нідерланди', 'The Netherlands': 'Нідерланди',
        'Belgium': 'Бельгія', 'Switzerland': 'Швейцарія', 'Sweden': 'Швеція',
        'Norway': 'Норвегія', 'Denmark': 'Данія', 'Austria': 'Австрія',
        'Czech Republic': 'Чеська Республіка', 'Czechia': 'Чеська Республіка',
        'Ireland': 'Ірландія', 'Republic of Ireland': 'Ірландія',
        'Hungary': 'Угорщина', 'Romania': 'Румунія', 'Finland': 'Фінляндія',
        'Iceland': 'Ісландія', 'Luxembourg': 'Люксембург', 'Portugal': 'Португалія', 'Greece': 'Греція',
        'Turkey': 'Туреччина', 'Türkiye': 'Туреччина', 'Israel': 'Ізраїль', 'Thailand': 'Таїланд',
        'Vietnam': "В'єтнам", 'Viet Nam': "В'єтнам",
        'Hong Kong': 'Гонконг', 'Hong Kong SAR China': 'Гонконг',
        'Taiwan': 'Тайвань', 'Macau': 'Макао', 'Macao': 'Макао',
        'Philippines': 'Філіппіни', 'Indonesia': 'Індонезія',
        'Malaysia': 'Малайзія', 'Singapore': 'Сінгапур', 'New Zealand': 'Нова Зеландія',
        'South Africa': 'Південна Африка', 'Egypt': 'Єгипет', 'Nigeria': 'Нігерія', 'Kenya': 'Кенія',
        'Morocco': 'Марокко', 'Tunisia': 'Туніс', 'Algeria': 'Алжир', 'Senegal': 'Сенегал', 'Ghana': 'Гана',
        'Chile': 'Чилі', 'Argentina': 'Аргентина', 'Colombia': 'Колумбія',
        'Venezuela': 'Венесуела', 'Venezuela, Bolivarian Republic of': 'Венесуела',
        'Peru': 'Перу', 'Cuba': 'Куба', 'Dominican Republic': 'Домініканська Республіка', 'Uruguay': 'Уругвай',
        'Bahamas': 'Багамські Острови', 'The Bahamas': 'Багамські Острови',
        'Puerto Rico': 'Пуерто-Рико', 'Jamaica': 'Ямайка', 'Costa Rica': 'Коста-Рика', 'Panama': 'Панама',
        'Ecuador': 'Еквадор', 'Paraguay': 'Парагвай', 'Guatemala': 'Гватемала', 'Honduras': 'Гондурас',
        'El Salvador': 'Сальвадор', 'Nicaragua': 'Нікарагуа', 'Bolivia': 'Болівія',
        'Bolivia, Plurinational State of': 'Болівія',
        'Bulgaria': 'Болгарія', 'Croatia': 'Хорватія', 'Serbia': 'Сербія', 'Slovakia': 'Словаччина',
        'Slovenia': 'Словенія', 'Bosnia and Herzegovina': 'Боснія і Герцеговина', 'North Macedonia': 'Північна Македонія',
        'Macedonia': 'Північна Македонія',
        'Montenegro': 'Чорногорія', 'Estonia': 'Естонія', 'Latvia': 'Латвія', 'Lithuania': 'Литва',
        'Belarus': 'Білорусь', 'Georgia': 'Грузія', 'Kazakhstan': 'Казахстан', 'Armenia': 'Вірменія',
        'Azerbaijan': 'Азербайджан', 'Uzbekistan': 'Узбекистан',
        'Moldova': 'Молдова', 'Moldova, Republic of': 'Молдова',
        'Iran': 'Іран', 'Iran, Islamic Republic of': 'Іран',
        'Syria': 'Сирія', 'Syrian Arab Republic': 'Сирія',
        'Pakistan': 'Пакистан', 'Bangladesh': 'Бангладеш', 'Sri Lanka': 'Шрі-Ланка', 'Nepal': 'Непал',
        'Afghanistan': 'Афганістан', 'Iraq': 'Ірак', 'Jordan': 'Йорданія', 'Lebanon': 'Ліван',
        'Palestine': 'Палестина', 'Palestine, State of': 'Палестина', 'Palestinian Territory, Occupied': 'Палестина',
        'United Arab Emirates': 'ОАЕ', 'Saudi Arabia': 'Саудівська Аравія', 'Qatar': 'Катар', 'Kuwait': 'Кувейт',
        'Oman': 'Оман', 'Bahrain': 'Бахрейн', 'Yemen': 'Ємен',
        'Libya': 'Лівія', 'Ethiopia': 'Ефіопія', 'Tanzania': 'Танзанія', 'Tanzania, United Republic of': 'Танзанія',
        'Cambodia': 'Камбоджа', 'Myanmar': "М'янма", 'Mongolia': 'Монголія',
        "Lao People's Democratic Republic": 'Лаос', 'Laos': 'Лаос',
        'Brunei Darussalam': 'Бруней', 'Brunei': 'Бруней',
        'Cyprus': 'Кіпр', 'Malta': 'Мальта', 'Monaco': 'Монако', 'Liechtenstein': 'Ліхтенштейн', 'Andorra': 'Андорра',
        'Democratic Republic of the Congo': 'ДР Конго', 'Congo, The Democratic Republic of the': 'ДР Конго',
        'Republic of the Congo': 'Республіка Конго', 'Congo': 'Республіка Конго'
    };

    const GENRE_UA = {
        'Action': 'Бойовик', 'Adventure': 'Пригоди', 'Animation': 'Анімація', 'Comedy': 'Комедія',
        'Crime': 'Кримінал', 'Documentary': 'Документальний', 'Drama': 'Драма', 'Family': 'Сімейний',
        'Fantasy': 'Фентезі', 'History': 'Історичний', 'Horror': 'Жахи', 'Music': 'Музичний',
        'Mystery': 'Детектив', 'Romance': 'Мелодрама', 'Science Fiction': 'Наукова фантастика',
        'TV Movie': 'Телефільм', 'Thriller': 'Трилер', 'War': 'Воєнний', 'Western': 'Вестерн',
        'Action & Adventure': 'Пригоди', 'Kids': 'Дитячий', 'News': 'Новини', 'Reality': 'Реаліті-шоу',
        'Sci-Fi & Fantasy': 'Наукова фантастика', 'Soap': 'Серіал', 'Talk': 'Ток-шоу',
        'War & Politics': 'Війна і політика'
    };

    function hasCyrillic(s) {
        return /[\u0400-\u04FF]/.test(safeStr(s));
    }

    function pickUkTranslationPayload(details) {
        if (!details || !details.translations) return null;
        const t = details.translations;
        const list = Array.isArray(t) ? t : t.translations;
        if (!Array.isArray(list)) return null;
        const row = list.find(t =>
            (t.iso_639_1 || '').toLowerCase() === 'uk' ||
            (t.iso_3166_1 || '').toUpperCase() === 'UA'
        );
        return row && row.data ? row.data : null;
    }

    function mapGenreNames(genres) {
        if (!Array.isArray(genres)) return '';
        return genres.map(g => {
            const name = (g && g.name ? g.name : g || '').trim();
            return GENRE_UA[name] || name;
        }).filter(Boolean).join(', ');
    }

    function mapGenreString(str) {
        const s = safeStr(str).trim();
        if (!s) return '';
        return s.split(',').map(part => {
            const name = part.trim();
            return GENRE_UA[name] || name;
        }).filter(Boolean).join(', ');
    }

    function normalizeTmdbType(raw) {
        const t = safeStr(raw).toLowerCase().replace(/[\s_-]+/g, '');
        if (t === 'tv' || t === 'series' || t === 'tvseries' || t === 'show') return 'tv';
        if (t === 'movie' || t === 'film' || t === 'movies') return 'movie';
        return t;
    }

    function collectAlternativeTitles(...detailResponses) {
        const out = [];
        const seen = new Set();
        for (const j of detailResponses) {
            if (!j || !j.alternative_titles) continue;
            const list = j.alternative_titles.titles || j.alternative_titles.results;
            if (!Array.isArray(list)) continue;
            for (const item of list) {
                const key = ((item.iso_3166_1 || '') + '|' + (item.title || '')).toLowerCase();
                if (!seen.has(key)) {
                    seen.add(key);
                    out.push(item);
                }
            }
        }
        return out;
    }

    function safeStr(val) {
        if (val == null) return '';
        if (typeof val === 'string') return val;
        return '';
    }

    // Short codes for film/TV audio/subtitle languages (used in subject/title)
    function langCode(lang) {
        const m = {
            uk: 'Ukr', ukrainian: 'Ukr', 'українська': 'Ukr', en: 'Eng', english: 'Eng', 'english (us)': 'Eng',
            de: 'Ger', german: 'Ger', fr: 'Fre', french: 'Fre', ru: 'Rus', russian: 'Rus',
            es: 'Spa', spanish: 'Spa', it: 'Ita', italian: 'Ita', ja: 'Jap', japanese: 'Jap',
            zh: 'Chi', chinese: 'Chi', mandarin: 'Chi', pt: 'Por', portuguese: 'Por',
            pl: 'Pol', polish: 'Pol', ko: 'Kor', korean: 'Kor', hi: 'Hin', hindi: 'Hin',
            tr: 'Tur', turkish: 'Tur', ar: 'Ara', arabic: 'Ara', th: 'Tha', thai: 'Tha',
            vi: 'Vie', vietnamese: 'Vie', nl: 'Dut', dutch: 'Dut', sv: 'Swe', swedish: 'Swe',
            hu: 'Hun', hungarian: 'Hun', he: 'Heb', hebrew: 'Heb', el: 'Gre', greek: 'Gre',
            cs: 'Cze', czech: 'Cze', ro: 'Rom', romanian: 'Rom', fi: 'Fin', finnish: 'Fin',
            da: 'Dan', danish: 'Dan', no: 'Nor', norwegian: 'Nor', id: 'Ind', indonesian: 'Ind',
            ms: 'May', malay: 'May', tl: 'Tag', tagalog: 'Tag', filipino: 'Tag',
            bn: 'Ben', bengali: 'Ben', fa: 'Per', persian: 'Per', ur: 'Urd', urdu: 'Urd'
        };
        const n = safeStr(lang).trim().toLowerCase();
        return m[n] || n || '—';
    }

    // Name (subject): BDRip | BDRemux | WEBDL | etc.   Dropdown (f11): any web → 18 WEBDLRip, any bluray → 16 BDRip
    function qualityFromBasename(basename, map) {
        const b = safeStr(basename).toLowerCase();
        const isWeb = /webdl|web-dl|webrip|web\s*rip|hdtv|hdrip/i.test(b);
        const isRemux = /remux|bluray\s*remux|bdremux/i.test(b);
        const isBluray = /bdrip|blu-ray|bluray|blu\s*ray/i.test(b);
        let nameLabel, dropdownValue;

        if (map) {
            if (isWeb) {
                dropdownValue = map['WEB-DL'] || '4';
                nameLabel = 'WEB-DL';
            } else if (isRemux) {
                dropdownValue = map['BDRip'] || '2';
                nameLabel = 'BDRemux';
            } else {
                dropdownValue = map['BDRip'] || '2';
                nameLabel = 'BDRip';
            }
            return { value: dropdownValue, label: nameLabel };
        }

        if (isWeb) {
            nameLabel = 'WEB-DL';
            dropdownValue = '18'; // WEBDLRip
        } else if (isRemux) {
            nameLabel = 'BDRemux';
            dropdownValue = '16'; // BDRip (any bluray → BDRip in dropdown)
        } else if (isBluray) {
            nameLabel = 'BDRip';
            dropdownValue = '16';
        } else {
            nameLabel = 'BDRip';
            dropdownValue = '16';
        }
        return { value: dropdownValue, label: nameLabel };
    }

    function dubTypeFromBasename(basename) {
        const b = safeStr(basename).toLowerCase();
        if (/-svo/.test(b)) return 'SVO';
        if (/-dvo/.test(b)) return 'DVO';
        if (/-dub/.test(b)) return 'DUB';
        return 'MVO';
    }

    function getDubTypeFromTrack(track, fallback) {
        const t = (safeStr(track.Title) + ' ' + safeStr(track.Title_Commercial_IfAny)).toLowerCase();
        if (/dvo|двогол/.test(t)) return 'DVO';
        if (/svo|одногол/.test(t)) return 'SVO';
        if (/mvo|багатогол/.test(t)) return 'MVO';
        if (/\bdub\b|дубляж|професійний/.test(t)) return 'DUB';
        return fallback;
    }

    function durationFromSeconds(sec) {
        const s = Math.floor(Number(sec) || 0);
        const h = Math.floor(s / 3600);
        const m = Math.floor((s % 3600) / 60);
        const ss = s % 60;
        return [h, m, ss].map(n => String(n).padStart(2, '0')).join(':');
    }

    function getBasename(meta) {
        const path = meta.path || '';
        const filelist = meta.filelist;
        if (Array.isArray(filelist) && filelist.length) {
            const first = filelist[0];
            return first.split(/[/\\]/).pop() || path.split(/[/\\]/).pop() || '';
        }
        return path.split(/[/\\]/).pop() || meta.uuid || '';
    }

    function getImdbUrl(meta) {
        const info = meta.imdb_info;
        if (info && info.imdb_url) return info.imdb_url;
        const id = meta.imdb_id != null ? meta.imdb_id : meta.imdb;
        if (id != null && id !== '') return 'https://www.imdb.com/title/tt' + String(id).replace(/^tt/i, '') + '/';
        return '';
    }

    function getImdbIdStr(meta) {
        const info = meta.imdb_info;
        if (info && info.imdbID) return String(info.imdbID).replace(/^tt/i, '');
        const id = meta.imdb_id != null ? meta.imdb_id : meta.imdb;
        if (id != null && id !== '') return String(id).replace(/^tt/i, '');
        return '';
    }

    function getCountries(meta) {
        if (meta._tmdb && meta._tmdb.production_countries) return meta._tmdb.production_countries;
        const arr = meta.production_countries;
        if (!Array.isArray(arr)) return '';
        return arr.map(c => COUNTRY_UA[c.name] || c.name).filter(Boolean).join(', ');
    }

    function getCompanies(meta) {
        if (meta._tmdb && meta._tmdb.production_companies) return meta._tmdb.production_companies;
        const arr = meta.production_companies;
        if (!Array.isArray(arr)) return '';
        return arr.map(c => c.name).slice(0, 5).join(', ');
    }

    function getGenres(meta) {
        if (meta._tmdb && meta._tmdb.genres) return meta._tmdb.genres;
        return mapGenreString(meta.genres || '');
    }

    function getDirectors(meta) {
        if (meta._tmdb && meta._tmdb.director) return meta._tmdb.director;
        const d = meta.tmdb_directors;
        if (Array.isArray(d)) return d.join(', ');
        const imdb = meta.imdb_info && meta.imdb_info.directors;
        if (Array.isArray(imdb)) return imdb.join(', ');
        return '';
    }

    function getCast(meta, limit = 10) {
        if (meta._tmdb && meta._tmdb.cast) return meta._tmdb.cast;
        const c = meta.tmdb_cast;
        if (Array.isArray(c)) return c.slice(0, limit).join(', ');
        const imdb = meta.imdb_info && meta.imdb_info.stars;
        if (Array.isArray(imdb)) return imdb.slice(0, limit).join(', ');
        return '';
    }

    function getOverview(meta) {
        if (meta._tmdb && meta._tmdb.overview) return meta._tmdb.overview;
        const plot = (meta.overview || (meta.imdb_info && meta.imdb_info.plot) || '').trim();
        return plot;
    }

    function getReleaseTitle(meta) {
        const t = meta._tmdb;
        if (t && t.title_uk) return t.title_uk.trim();
        const candidates = [meta.regex_title, meta.title, meta.imdb_info && meta.imdb_info.Title];
        for (const c of candidates) {
            const s = safeStr(c).trim();
            if (s && hasCyrillic(s)) return s;
        }
        return safeStr(meta.regex_title || meta.title || '').trim();
    }

    function tmdbUkrainianWarnings(tmdb) {
        if (!tmdb) return [];
        const w = [];
        if (!tmdb.title_uk) w.push('немає української назви в TMDB');
        else if (!hasCyrillic(tmdb.title_uk)) w.push('назва без кирилиці (немає UA перекладу в TMDB)');
        if (!tmdb.overview) w.push('немає опису');
        else if (!hasCyrillic(tmdb.overview)) w.push('опис не українською (немає UA перекладу в TMDB)');
        return w;
    }

    function metaNeedsTmdb(meta) {
        return !!(meta.tmdb_id || meta.tmdb || meta.imdb_id || meta.imdb ||
            (meta.imdb_info && meta.imdb_info.imdbID));
    }

    // ——— External links: TMDB, IMDb, MAL, AniList, Letterboxd, Trakt
    function buildTmdbUrl(tmdbId, type) {
        if (!tmdbId) return '';
        const path = (type === 'tv') ? 'tv' : 'movie';
        return `https://www.themoviedb.org/${path}/${tmdbId}`;
    }

    function buildLetterboxdUrl(imdbIdStr) {
        if (!imdbIdStr) return '';
        const tt = imdbIdStr.startsWith('tt') ? imdbIdStr : 'tt' + imdbIdStr;
        return `https://letterboxd.com/imdb/${tt}/`;
    }

    function buildMalUrl(malId) {
        if (!malId) return '';
        return `https://myanimelist.net/anime/${malId}`;
    }

    function buildAnilistUrl(anilistId) {
        if (!anilistId) return '';
        return `https://anilist.co/anime/${anilistId}`;
    }

    function buildTraktImdbUrl(imdbIdStr) {
        if (!imdbIdStr) return '';
        const tt = imdbIdStr.startsWith('tt') ? imdbIdStr : 'tt' + imdbIdStr;
        return `https://trakt.tv/search/imdb/${tt}`;
    }

    async function fetchMalIdByTitle(title, year) {
        const q = [title, year].filter(Boolean).join(' ');
        if (!q.trim()) return null;
        try {
            const url = `https://api.jikan.moe/v4/anime?q=${encodeURIComponent(q)}&limit=3`;
            const res = await fetch(url);
            if (!res.ok) return null;
            const data = await res.json();
            const results = data.data || [];
            const match = results.find(a => {
                const y = a.year || (a.aired && a.aired.prop && a.aired.prop.from && a.aired.prop.from.year);
                return !year || String(y) === String(year);
            }) || results[0];
            return match ? match.mal_id : null;
        } catch (e) {
            return null;
        }
    }

    async function fetchAnilistIdByTitle(title, year) {
        const search = [title, year].filter(Boolean).join(' ');
        if (!search.trim()) return null;
        try {
            const query = `query($s: String) { Page(page: 1, perPage: 5) { media(search: $s, type: ANIME) { id title { romaji } startDate { year } } } }`;
            const res = await fetch('https://graphql.anilist.co', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ query, variables: { s: search } })
            });
            if (!res.ok) return null;
            const data = await res.json();
            const list = data.data && data.data.Page && data.data.Page.media;
            if (!Array.isArray(list) || !list.length) return null;
            const match = list.find(m => !year || (m.startDate && String(m.startDate.year) === String(year))) || list[0];
            return match ? match.id : null;
        } catch (e) {
            return null;
        }
    }

    /** Build link set from meta (sync part). Resolve MAL/AniList async and then call onUpdate. */
    function getInitialLinks(meta) {
        const imdbUrl = getImdbUrl(meta);
        const imdbIdStr = getImdbIdStr(meta);
        const t = meta._tmdb;
        const tmdbId = (t && t.tmdb_id) || meta.tmdb_id || meta.tmdb;
        const tmdbType = normalizeTmdbType((t && t.tmdb_type) || meta.tmdb_type || meta.category || '') || 'movie';
        const title = (t && t.title_uk) || (t && t.original_title) || meta.original_title ||
            (meta.imdb_info && meta.imdb_info.Title) || meta.title || '';
        const year = String((t && t.year) || meta.year || '').slice(0, 4);

        return {
            imdb: { url: imdbUrl, label: 'IMDb' },
            tmdb: { url: buildTmdbUrl(tmdbId, tmdbType), label: 'TMDB' },
            letterboxd: { url: buildLetterboxdUrl(imdbIdStr), label: 'Letterboxd' },
            mal: { url: buildMalUrl(meta.mal_id), label: 'MAL' },
            anilist: { url: '', label: 'AniList' },
            trakt: { url: buildTraktImdbUrl(imdbIdStr), label: 'Trakt' },
            _imdbIdStr: imdbIdStr,
            _title: title,
            _year: year
        };
    }

    async function resolveExtraLinks(links) {
        const out = { ...links };
        if (!links.mal.url && (links._title || links._year)) {
            const malId = await fetchMalIdByTitle(links._title, links._year);
            if (malId) out.mal = { url: buildMalUrl(malId), label: 'MAL' };
        }
        if (!links.anilist.url && (links._title || links._year)) {
            const anilistId = await fetchAnilistIdByTitle(links._title, links._year);
            if (anilistId) out.anilist = { url: buildAnilistUrl(anilistId), label: 'AniList' };
        }
        return out;
    }

    function getScreenshotsBBCode(meta) {
        const list = meta.image_list;
        if (!Array.isArray(list) || !list.length) return '';
        return list.map(item => {
            const raw = item.raw_url;
            const thumb = item.img_url;
            if (raw && thumb) return `[url=${raw}][img]${thumb}[/img][/url]`;
            const url = raw || thumb || '';
            return url ? `[img]${url}[/img]` : '';
        }).filter(Boolean).join(' ');
    }

    // For series/anime: episode duration (hh:mm or mm:ss) and episode count from meta
    function getEpisodeDurationAndCount(meta) {
        const tracks = getTracks(meta);
        const general = tracks.general;
        let durationStr = '';
        let countStr = '';
        if (general && general.Duration) {
            const sec = parseFloat(general.Duration);
            durationStr = durationFromSeconds(sec);
        }
        const episode = meta.episode;
        if (episode != null && episode !== '') {
            countStr = String(episode);
        } else if (Array.isArray(meta.filelist) && meta.filelist.length > 1) {
            countStr = String(meta.filelist.length);
        }
        return { durationStr, countStr };
    }

    // ——— TMDB: Ukrainian (uk-UA) first; translations + UA alt titles; en-US only as last resort for text
    async function fetchTmdbData(apiKey, meta, options) {
        const key = (apiKey || '').trim();
        if (!key) return null;
        const formHint = options && options.formHint;
        const imdbId = meta.imdb_id != null ? meta.imdb_id : (meta.imdb_info && meta.imdb_info.imdbID) || meta.imdb;
        const imdbStr = imdbId != null && imdbId !== '' ? ('tt' + String(imdbId).replace(/^tt/i, '')) : '';
        let tmdbId = meta.tmdb_id != null ? meta.tmdb_id : meta.tmdb;
        let type = normalizeTmdbType(meta.tmdb_type || meta.category || '');
        if (!type && (formHint === 'series' || formHint === 'anime')) type = 'tv';
        if (!type && (formHint === 'main' || formHint === 'video_films_hd_ukrainian' || formHint === 'video_animation_hd_ukrainian')) type = 'movie';

        if (!tmdbId && imdbStr) {
            const findUrl = `https://api.themoviedb.org/3/find/${imdbStr}?api_key=${encodeURIComponent(key)}&external_source=imdb_id`;
            let findRes;
            try {
                findRes = await fetch(findUrl);
            } catch (e) {
                throw new Error('TMDB find: ' + (e.message || 'network error'));
            }
            if (!findRes.ok) throw new Error('TMDB find: ' + findRes.status);
            const findData = await findRes.json();
            const movieResults = findData.movie_results || [];
            const tvResults = findData.tv_results || [];
            if (type === 'tv' && tvResults.length) {
                tmdbId = tvResults[0].id;
                type = 'tv';
            } else if (movieResults.length && type !== 'tv') {
                tmdbId = movieResults[0].id;
                type = 'movie';
            } else if (tvResults.length) {
                tmdbId = tvResults[0].id;
                type = 'tv';
            } else if (movieResults.length) {
                tmdbId = movieResults[0].id;
                type = 'movie';
            }
            if (!tmdbId) return null;
        } else if (tmdbId) {
            if (type !== 'movie' && type !== 'tv') {
                type = (formHint === 'series' || formHint === 'anime') ? 'tv' : 'movie';
            }
        } else {
            return null;
        }

        const append = 'credits,alternative_titles,translations';
        const langUk = `https://api.themoviedb.org/3/${type}/${tmdbId}?api_key=${encodeURIComponent(key)}&append_to_response=${append}&language=uk-UA`;
        const langEn = `https://api.themoviedb.org/3/${type}/${tmdbId}?api_key=${encodeURIComponent(key)}&append_to_response=${append}&language=en-US`;
        let uk, en;
        try {
            [uk, en] = await Promise.all([
                fetch(langUk).then(r => r.ok ? r.json() : null),
                fetch(langEn).then(r => r.ok ? r.json() : null)
            ]);
        } catch (e) {
            throw new Error('TMDB fetch: ' + (e.message || 'network error'));
        }
        if (uk && uk.success === false) throw new Error('TMDB: ' + (uk.status_message || 'API error'));
        const base = uk || en;
        if (!base) return null;

        const titleField = type === 'tv' ? 'name' : 'title';
        const originalField = type === 'tv' ? 'original_name' : 'original_title';
        const dateField = type === 'tv' ? 'first_air_date' : 'release_date';
        const ukTrans = pickUkTranslationPayload(uk) || pickUkTranslationPayload(en);
        const mainTitleUk = ((uk && uk[titleField]) || '').trim();
        const mainTitleEn = ((en && en[titleField]) || '').trim();
        let originalTitle = (base[originalField] || '').trim();
        const year = (base[dateField] || '').slice(0, 4);

        const altList = collectAlternativeTitles(uk, en);
        const hasJapaneseChars = (s) => /[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/.test(s);
        const ukTitles = [];
        const addTitle = (t) => {
            const s = (t || '').trim();
            if (s && !ukTitles.includes(s)) ukTitles.push(s);
        };
        const transTitle = ukTrans && (ukTrans[titleField] || '').trim();
        if (transTitle) addTitle(transTitle);
        for (const item of altList) {
            const code = (item.iso_3166_1 || '').toUpperCase();
            if (code === 'UA') addTitle(item.title);
        }
        if (mainTitleUk && (hasCyrillic(mainTitleUk) || !mainTitleEn || mainTitleUk !== mainTitleEn)) {
            addTitle(mainTitleUk);
        } else if (!ukTitles.length && mainTitleUk) {
            addTitle(mainTitleUk);
        }
        const titleUk = ukTitles.join(' / ');
        if (hasJapaneseChars(originalTitle) && altList.length) {
            const firstRomaji = altList.find(item => {
                const t = (item.title || '').trim();
                return t && !hasJapaneseChars(t);
            });
            if (firstRomaji && firstRomaji.title) originalTitle = firstRomaji.title.trim();
        }

        let overview = (ukTrans && (ukTrans.overview || '').trim()) || '';
        if (!overview && uk) overview = (uk.overview || '').trim();
        if (!overview && en) overview = (en.overview || '').trim();

        const genreSource = (uk && Array.isArray(uk.genres) && uk.genres.length)
            ? uk.genres
            : (en && en.genres) || base.genres;
        const genres = mapGenreNames(genreSource);

        const countriesSource = base.production_countries;
        const productionCountries = Array.isArray(countriesSource)
            ? countriesSource.map(c => COUNTRY_UA[c.name] || c.name).filter(Boolean).join(', ')
            : '';
        const productionCompanies = Array.isArray(base.production_companies)
            ? base.production_companies.map(c => c.name).slice(0, 5).join(', ')
            : '';
        const credits = base.credits || {};
        const cast = (credits.cast || []).slice(0, 10).map(p => p.name || p.original_name || '').filter(Boolean).join(', ');
        let director = '';
        if (type === 'movie') {
            director = (credits.crew || []).filter(p => p.job === 'Director').map(p => p.name).join(', ');
        } else {
            const createdBy = base.created_by || [];
            director = Array.isArray(createdBy) ? createdBy.map(p => p.name).filter(Boolean).join(', ') : '';
        }

        return {
            genres,
            production_countries: productionCountries,
            production_companies: productionCompanies,
            overview,
            cast,
            director,
            title_uk: titleUk,
            original_title: originalTitle,
            year,
            tmdb_id: tmdbId,
            tmdb_type: type
        };
    }

    // ——— Mediainfo: first General + first Video + all Audio/Text
    function getTracks(meta) {
        const media = meta.mediainfo && meta.mediainfo.media;
        const track = media && media.track;
        if (!Array.isArray(track)) return { general: null, video: null, audio: [], text: [] };
        const general = track.find(t => t['@type'] === 'General') || null;
        const video = track.find(t => t['@type'] === 'Video') || null;
        const audio = track.filter(t => t['@type'] === 'Audio');
        const text = track.filter(t => t['@type'] === 'Text');
        return { general, video, audio, text };
    }

    // Toloka video codec f13: 7=H.264, 12=VPx (HEVC not listed → 7 or 12)
    // Toloka video codec f13: Default (7=H.264, 12=VPx) or Map-based
    function videoCodecToSelect(format, map) {
        const f = safeStr(format).toUpperCase();
        if (map) {
            for (const [key, val] of Object.entries(map)) {
                if (new RegExp(key, 'i').test(f)) return val;
            }
            return '0';
        }
        if (/AVC|H\.?264/.test(f)) return '7';
        if (/HEVC|H\.?265|VP9/.test(f)) return '12';
        return '7';
    }

    // Toloka audio language f18: 1=українська, 2=англійська, 9=французька, 8=російська, 3=італійська, 4=китайська, 5=корейська, 6=німецька, 7=польська, 10=фінська, 11=чеська, 12=японська
    const DEFAULT_AUDIO_LANG_MAP = {
        uk: '1', ukrainian: '1', 'українська': '1', 'ukrainian (ua)': '1', Ukrainian: '1',
        en: '2', english: '2', English: '2', it: '3', Italian: '3',
        zh: '4', Chinese: '4', ko: '5', Korean: '5', de: '6', German: '6',
        pl: '7', Polish: '7', ru: '8', Russian: '8', fr: '9', French: '9',
        fi: '10', Finnish: '10', cs: '11', Czech: '11', ja: '12', Japanese: '12'
    };

    function audioLangToSelect(lang, map) {
        const m = map || DEFAULT_AUDIO_LANG_MAP;
        const n = safeStr(lang).trim();
        let v = m[n] || m[n.toLowerCase()];
        if (v) return v;
        const firstWord = n.split(/[\s(\-]+/)[0];
        if (firstWord) v = m[firstWord] || m[firstWord.toLowerCase()];
        return v || '0';
    }

    // f19: 1=оригінал, 2=професійний дубльований, 3=багатоголосий закадровий, 4=двоголосий закадровий, 5=одноголосий закадровий, 6="гоблінський"
    function audioTypeToSelect(lang, dubType, map) {
        const isUa = /uk|ukrainian|україн/i.test(safeStr(lang));
        if (map) {
            if (!isUa) return map['ORIGINAL'] || '1';
            if (dubType === 'SVO') return map['SVO'] || '5';
            if (dubType === 'DVO') return map['DVO'] || '4';
            if (dubType === 'DUB') return map['DUB'] || '2';
            return map['MVO'] || '3';
        }
        if (!isUa) return '1'; // оригінал
        if (dubType === 'SVO') return '5';
        if (dubType === 'DVO') return '4';
        if (dubType === 'DUB') return '2';
        return '3'; // MVO
    }

    // f20: 3=AC3 2.0, 4=AC3 5.1, 7=DTS 2.0, 8=DTS 5.1, 9=DTS-HD 2.0, 10=DTS-HD 5.1, 11=DTS-HD 7.1, 12=FLAC
    function audioCodecToSelect(format, channels) {
        const f = safeStr(format).toLowerCase();
        const ch = String(channels != null ? channels : '');
        const is51 = /6|5\.1|5.1/.test(ch);
        const is20 = /2|2\.0|2.0|stereo/i.test(ch);
        if (/dts[- ]?hd|dtshd|master/i.test(f)) return is51 ? '10' : '9';
        if (/dts/i.test(f)) return is51 ? '8' : '7';
        if (/ac-?3|dolby\s*digital|e-?ac-?3/i.test(f)) return is51 ? '4' : '3';
        if (/flac/i.test(f)) return '12';
        if (/aac/i.test(f)) return is51 ? '2' : '1';
        return is51 ? '4' : '3';
    }

    // Subtitle language f25: same codes as audio
    function subLangToSelect(lang, map) {
        return audioLangToSelect(lang, map);
    }
    // f26: 1=вбудовані (жорсткі), 2=пререндерні, 3=програмні (м'які)
    function subTypeToSelect(format) {
        const f = safeStr(format).toLowerCase();
        if (/pgs|sup|vobsub/i.test(f)) return '2';
        if (/utf-?8|srt|ass|text/i.test(f)) return '3';
        return '3';
    }
    // f27: 8=*.srt, 2=*.ass, 10=*.sub, 11=*.sub + *.idx
    function subFormatToSelect(format) {
        const f = safeStr(format).toLowerCase();
        if (/utf-?8|srt/i.test(f)) return '8';
        if (/ass|ssa/i.test(f)) return '2';
        if (/pgs|sup/i.test(f)) return '10';
        if (/vobsub|idx/i.test(f)) return '11';
        return '8';
    }

    function setField(form, name, value) {
        const el = form.querySelector(`[name="${name}"]`);
        if (!el) return;
        if (el.tagName === 'SELECT') {
            const opt = Array.from(el.options).find(o => o.value === String(value));
            if (opt) opt.selected = true;
        } else if (el.type === 'checkbox' || el.type === 'radio') {
            el.checked = !!value;
        } else {
            el.value = value != null ? String(value) : '';
        }
    }

    function setFieldByIndex(form, name, index, value) {
        const els = form.querySelectorAll(`[name="${name}"]`);
        const el = els[index];
        if (!el) return;
        if (el.tagName === 'SELECT') {
            const opt = Array.from(el.options).find(o => o.value === String(value));
            if (opt) opt.selected = true;
        } else {
            el.value = value != null ? String(value) : '';
        }
    }

    // Clone table row so we have enough rows without clicking Toloka's + (avoids mlAddVal break)
    function ensureRows(form, rowSelector, count) {
        const first = form.querySelector(rowSelector);
        if (!first || count <= 1) return;
        const row = first.closest('tr');
        if (!row || !row.parentNode) return;
        const currentCount = form.querySelectorAll(rowSelector).length;
        for (let i = currentCount; i < count; i++) {
            const clone = row.cloneNode(true);
            row.parentNode.appendChild(clone);
        }
    }

    function fillVideoTrack(form, fields, video, videoCodecMap) {
        if (!video || !fields.video_codec) return;
        const codec = videoCodecToSelect(video.Format, videoCodecMap);
        const res = video.Width && video.Height ? `${video.Width} x ${video.Height}` : '';
        const bitrate = (video.BitRate && Number(video.BitRate) > 0) ? (Number(video.BitRate) / 1e6).toFixed(1) : '';
        setFieldByIndex(form, fields.video_codec, 0, codec);
        if (fields.video_res) setFieldByIndex(form, fields.video_res, 0, res);
        if (fields.video_bitrate) setFieldByIndex(form, fields.video_bitrate, 0, bitrate ? bitrate + ' мб/с' : '');
    }

    function fillAudioTracks(form, fields, audioTracks, langMap, audioTypeMap, dubType) {
        if (!fields.audio_lang || !audioTracks.length) return;
        ensureRows(form, `select[name="${fields.audio_lang}"]`, audioTracks.length);
        audioTracks.forEach((a, i) => {
            const lang = safeStr(a.Language);
            const ch = a.Channels;
            const fmt = safeStr(a.Format_Commercial_IfAny || a.Format);
            const bitK = (a.BitRate && Number(a.BitRate) > 0) ? Math.round(Number(a.BitRate) / 1000) : 'VBR';
            const trackDubType = getDubTypeFromTrack(a, dubType);
            setFieldByIndex(form, fields.audio_lang, i, audioLangToSelect(lang, langMap));
            if (fields.audio_type) setFieldByIndex(form, fields.audio_type, i, audioTypeToSelect(lang, trackDubType, audioTypeMap));
            if (fields.audio_codec) setFieldByIndex(form, fields.audio_codec, i, audioCodecToSelect(fmt, ch));
            if (fields.audio_bitrate) setFieldByIndex(form, fields.audio_bitrate, i, bitK + (bitK === 'VBR' ? '' : ' кб/с'));
        });
    }

    function fillSubtitleTracks(form, fields, textTracks, langMap) {
        if (!fields.sub_lang || !textTracks.length) return;
        ensureRows(form, `select[name="${fields.sub_lang}"]`, textTracks.length);
        textTracks.forEach((tr, i) => {
            const subFmt = safeStr(tr.Format || tr.CodecID || '');
            setFieldByIndex(form, fields.sub_lang, i, subLangToSelect(tr.Language, langMap));
            if (fields.sub_type) setFieldByIndex(form, fields.sub_type, i, subTypeToSelect(subFmt));
            if (fields.sub_format) setFieldByIndex(form, fields.sub_format, i, subFormatToSelect(subFmt));
        });
    }

    // ——— Field Configuration ———
    // Defines field names/IDs for each category (what=...)
    const FORM_CONFIGS = {
        'main': {
            type: 'movie',
            fields: {
                genres: 'f1', countries: 'f2', imdb: 'f4[]', companies: 'f6', directors: 'f7', cast: 'f8', overview: 'f9',
                duration: 'f10', quality: 'f11', video_codec: 'f13[]', video_res: 'f14[]', video_bitrate: 'f15[]',
                audio_lang: 'f18[]', audio_type: 'f19[]', audio_codec: 'f20[]', audio_bitrate: 'f21[]',
                sub_lang: 'f25[]', sub_type: 'f26[]', sub_format: 'f27[]',
                screenshots: 'f29', source_dubbing: 'f23',
                // hardcoded values from original script
                val_f31: { name: 'f31[]', value: '18' },
                val_f32: { name: 'f32[]', value: '14' },
                val_f34: { name: 'f34', value: '11' }
            }
        },
        'series': {
            type: 'series',
            fields: {
                genres: 'f1', countries: 'f2', imdb: 'f4[]', companies: 'f6', directors: 'f7', cast: 'f8', overview: 'f9',
                ep_duration: 'f11[]', ep_count: 'f12[]', ep_list: 'f14', quality: 'f15',
                video_codec: 'f17[]', video_res: 'f18[]', video_bitrate: 'f19[]',
                audio_lang: 'f22[]', audio_type: 'f23[]', audio_codec: 'f24[]', audio_bitrate: 'f25[]',
                sub_lang: 'f29[]', sub_type: 'f30[]', sub_format: 'f31[]',
                screenshots: 'f33', source_dubbing: 'f27',
                val_f35: { name: 'f35[]', value: '18' },
                val_f36: { name: 'f36[]', value: '14' },
                val_f38: { name: 'f38', value: '11' }
            }
        },
        'anime': {
            type: 'anime',
            fields: {
                genres: 'f1', countries: 'f2', imdb: 'f4[]', companies: 'f10', directors: 'f11', cast: 'f12', overview: 'f13',
                ep_duration: 'f15[]', ep_count: 'f16[]', ep_list: 'f18', quality: 'f19',
                video_codec: 'f21[]', video_res: 'f22[]', video_bitrate: 'f23[]',
                audio_lang: 'f26[]', audio_type: 'f27[]', audio_codec: 'f28[]', audio_bitrate: 'f29[]',
                sub_lang: 'f33[]', sub_type: 'f34[]', sub_format: 'f35[]',
                screenshots: 'f38', mediainfo: 'f37', source_dubbing: 'f31',
                val_f40: { name: 'f40[]', value: '18' },
                val_f41: { name: 'f41[]', value: '14' },
                val_f43: { name: 'f43', value: '11' }
            }
        },
        'video_films_hd_ukrainian': {
            type: 'movie',
            fields: {
                // HD specific mapping based on user input
                covers: 'f0[]', genres: 'f1', countries: 'f2', imdb: 'f4[]', companies: 'f6', directors: 'f7', cast: 'f8', overview: 'f9',
                duration: 'f10', quality: 'f11',
                video_codec: 'f13[]', video_res: 'f14[]', video_bitrate: 'f15[]',
                audio_lang: 'f18[]', audio_type: 'f19[]', audio_codec: 'f20[]', audio_bitrate: 'f21[]',
                sub_lang: 'f25[]', sub_type: 'f26[]', sub_format: 'f27[]',
                screenshots: 'f30', mediainfo: 'f29'
            },
            lang_map: {
                uk: '1', Ukrainian: '1', en: '2', English: '2', it: '3', Italian: '3',
                zh: '4', Chinese: '4', ko: '5', Korean: '5', de: '6', German: '6',
                pl: '7', Polish: '7', ru: '8', Russian: '8', fr: '9', French: '9',
                fi: '10', Finnish: '10', cs: '11', Czech: '11', ja: '12', Japanese: '12'
            },
            video_codec_map: {
                // 1=ASF, 2=DivX 5.x, 3=DivX 6.x, 4=H.263, 5=H.264, 6=XviD, 7=VC-1, 8=VPx, 9=WMV
                'AVC|H\\.?264': '5',
                'HEVC|H\\.?265': '5', // Fallback to H.264 as HEVC isn't listed
                'XviD': '6',
                'DivX': '3',
                'VC-1': '7',
                'WMV': '9',
                'VP\\d': '8',
                'ASF': '1',
                'H\\.?263': '4'
            },
            audio_type_map: {
                'ORIGINAL': '1',
                'DUB': '2',
                'MVO': '3',
                'DVO': '4',
                'SVO': '5'
            },
            quality_map: {
                'WEB-DL': '4',
                'BDRip': '2'
            }
        },
        'video_animation_hd_ukrainian': {
            type: 'movie',
            fields: {
                covers: 'f0[]', genres: 'f1', countries: 'f2', imdb: 'f4[]', companies: 'f6', directors: 'f7', cast: 'f8', overview: 'f9',
                duration: 'f10', quality: 'f11',
                video_codec: 'f13[]', video_res: 'f14[]', video_bitrate: 'f15[]',
                audio_lang: 'f18[]', audio_type: 'f19[]', audio_codec: 'f20[]', audio_bitrate: 'f21[]',
                sub_lang: 'f25[]', sub_type: 'f26[]', sub_format: 'f27[]',
                screenshots: 'f30', mediainfo: 'f29',
                val_f23: { name: 'f23', value: '46' },
                val_f32: { name: 'f32[]', value: '18' },
                val_f33: { name: 'f33[]', value: '14' },
                val_f35: { name: 'f35', value: '11' }
            },
            lang_map: {
                uk: '1', Ukrainian: '1', en: '2', English: '2', it: '3', Italian: '3',
                zh: '4', Chinese: '4', ko: '5', Korean: '5', de: '6', German: '6',
                pl: '7', Polish: '7', ru: '8', Russian: '8', fr: '9', French: '9',
                fi: '10', Finnish: '10', cs: '11', Czech: '11', ja: '12', Japanese: '12'
            },
            video_codec_map: {
                // f13: 1=ASF, 2=DivX 5.x, 3=DivX 6.x, 4=H.263, 5=H.264, 6=XviD, 7=VC-1, 8=VPx, 9=WMV
                'AVC|H\\.?264': '5',
                'HEVC|H\\.?265': '5',
                'XviD': '6',
                'DivX': '3',
                'VC-1': '7',
                'WMV': '9',
                'VP\\d': '8',
                'ASF': '1',
                'H\\.?263': '4'
            },
            audio_type_map: {
                'ORIGINAL': '1',
                'DUB': '2',
                'MVO': '3',
                'DVO': '4',
                'SVO': '5'
            },
            quality_map: {
                // f11: 1=HDTVRip, 2=BDRip, 3=HDDVDRip, 4=WEBDLRip. qualityFromBasename uses 'WEB-DL' and 'BDRip' keys.
                'WEB-DL': '4',
                'BDRip': '2',
                'HDTVRip': '1',
                'HDDVDRip': '3',
                'WEBDLRip': '4'
            }
        }
    };

    function getFormType() {
        const urlParams = (typeof location !== 'undefined' && location.search) ? new URLSearchParams(location.search) : null;
        const what = urlParams ? urlParams.get('what') : '';

        if (what === 'video_series') return 'series';
        if (what === 'video_anime') return 'anime';
        if (what === 'video_films_hd_ukrainian') return 'video_films_hd_ukrainian';
        if (what === 'video_animation_hd_ukrainian') return 'video_animation_hd_ukrainian';
        // Add more exact matches here if needed

        return 'main'; // default
    }

    function populateForm(form, meta) {
        const formType = getFormType();
        const config = FORM_CONFIGS[formType] || FORM_CONFIGS['main'];
        const fields = config.fields;
        const langMap = config.lang_map;
        const videoCodecMap = config.video_codec_map;
        const audioTypeMap = config.audio_type_map;
        const qualityMap = config.quality_map;

        const basename = getBasename(meta);
        const quality = qualityFromBasename(basename, qualityMap);
        const dubType = dubTypeFromBasename(basename);
        const tracks = getTracks(meta);

        // Subject filling (common)
        const t = meta._tmdb;
        const title = getReleaseTitle(meta);
        const originalTitle = (t && t.original_title) || (meta.secondary_title || meta.regex_secondary_title || meta.original_title || (meta.imdb_info && meta.imdb_info.aka) || '').trim();
        const year = String((t && t.year) || meta.year || (meta.release_date || '').slice(0, 4) || '').slice(0, 4);
        const resolution = (meta.resolution || '').trim() || '1080p';
        // const service = (meta.service || '').trim(); // Service removed from subject per request

        // Codec in title: add H.265 / VC-1 / AV1 after resolution when present
        let codecInTitle = '';
        if (tracks.video) {
            const vf = safeStr(tracks.video.Format || tracks.video.CodecID || '').toUpperCase();
            if (/HEVC|H\.?265/.test(vf)) codecInTitle = 'H.265';
            else if (/VC-1/.test(vf)) codecInTitle = 'VC-1';
            else if (/AV1/.test(vf)) codecInTitle = 'AV1';
        }

        // Helper to get unique ordered langs
        const getOrderedLangs = (trackList) => {
            const codes = [];
            if (!trackList) return codes;
            trackList.forEach(t => {
                const code = langCode(t.Language);
                if (code && code !== '—' && !codes.includes(code)) {
                    codes.push(code);
                }
            });
            return codes;
        };

        const audioLangs = getOrderedLangs(tracks.audio);
        const subLangs = getOrderedLangs(tracks.text);
        let titleSuffix = audioLangs.join('/');
        if (subLangs.length) titleSuffix += ' | Sub ' + subLangs.join('/');

        const qualityPart = quality.label;
        const subject = [title, originalTitle].filter(Boolean).join(' / ') + (year ? ` (${year}) ` : ' ') + qualityPart + ' ' + resolution + (codecInTitle ? ' ' + codecInTitle : '') + ' ' + titleSuffix;
        setField(form, 'subject', subject.trim());

        const imdbUrl = getImdbUrl(meta);
        const screenshots = getScreenshotsBBCode(meta);

        // Fill common text fields
        if (fields.genres) setField(form, fields.genres, getGenres(meta));
        if (fields.countries) setField(form, fields.countries, getCountries(meta));
        if (fields.imdb) setField(form, fields.imdb, imdbUrl);
        if (fields.companies) setField(form, fields.companies, getCompanies(meta));
        if (fields.directors) setField(form, fields.directors, getDirectors(meta));
        if (fields.cast) setField(form, fields.cast, getCast(meta));
        if (fields.overview) setField(form, fields.overview, getOverview(meta));

        // Fill static values defined in config (like '18', '14', '11')
        Object.keys(fields).forEach(k => {
            if (k.startsWith('val_')) {
                const item = fields[k];
                setField(form, item.name, item.value);
            }
        });

        // Specific Logic types
        if (config.type === 'movie') {
            if (fields.duration && tracks.general && tracks.general.Duration) {
                const sec = parseFloat(tracks.general.Duration);
                setField(form, fields.duration, durationFromSeconds(sec));
            }
            if (fields.quality) setField(form, fields.quality, quality.value);

            fillVideoTrack(form, fields, tracks.video, videoCodecMap);
            fillAudioTracks(form, fields, tracks.audio, langMap, audioTypeMap, dubType);
            fillSubtitleTracks(form, fields, tracks.text, langMap);

            if (fields.source_dubbing) setField(form, fields.source_dubbing, '45');
        } else if (config.type === 'series' || config.type === 'anime') {
            const ep = getEpisodeDurationAndCount(meta);
            if (fields.ep_duration) setFieldByIndex(form, fields.ep_duration, 0, ep.durationStr);
            if (fields.ep_count) setFieldByIndex(form, fields.ep_count, 0, ep.countStr);
            if (fields.ep_list) setField(form, fields.ep_list, ''); // Leave empty for user

            if (fields.quality) setField(form, fields.quality, quality.value);

            fillVideoTrack(form, fields, tracks.video, videoCodecMap);
            fillAudioTracks(form, fields, tracks.audio, langMap, audioTypeMap, dubType);
            if (fields.source_dubbing) setField(form, fields.source_dubbing, '45');
            fillSubtitleTracks(form, fields, tracks.text, langMap);
        }

        // Final fields (Screenshots, MediaInfo)
        if (fields.screenshots) setField(form, fields.screenshots, screenshots);
        if (fields.mediainfo && meta.mediainfo_raw) {
            setField(form, fields.mediainfo, meta.mediainfo_raw);
        }
    }

    function findForm() {
        return document.querySelector('form[name="post"]') || document.querySelector('form[enctype="multipart/form-data"]');
    }

    const LINKS_PANEL_ID = 'toloka-fill-links-panel';

    function getLinksPanel() {
        return document.getElementById(LINKS_PANEL_ID);
    }

    function renderLinksPanel(container, links) {
        if (!container) return;
        const entries = [
            links.imdb,
            links.tmdb,
            links.mal,
            links.anilist,
            links.letterboxd,
            links.trakt
        ];
        container.innerHTML = '';
        const title = document.createElement('div');
        title.style.fontWeight = 'bold';
        title.style.marginBottom = '8px';
        title.style.color = '#333';
        title.textContent = 'Посилання';
        container.appendChild(title);
        entries.forEach(entry => {
            if (!entry || !entry.label) return;
            const row = document.createElement('div');
            row.style.marginBottom = '6px';
            const a = document.createElement('a');
            a.href = entry.url || '#';
            a.textContent = entry.label;
            a.target = '_blank';
            a.rel = 'noopener noreferrer';
            if (!entry.url) {
                a.style.color = '#999';
                a.href = 'javascript:void(0)';
            }
            row.appendChild(a);
            container.appendChild(row);
        });
    }

    function injectUI() {
        const form = findForm();
        if (!form) return;

        const table = form.querySelector('table.forumline');
        if (!table || !table.tBodies[0]) return;

        const thead = table.querySelector('th.thHead');
        let panel = document.getElementById('toloka-fill-panel');
        let btn = document.getElementById('toloka-fill-btn');

        if (panel && btn) return;

        const firstRow = table.rows[1];
        btn = document.createElement('button');
        btn.type = 'button';
        btn.id = 'toloka-fill-btn';
        btn.className = 'mainoption';
        btn.textContent = 'Заповнити з папки (meta.json)';
        btn.style.marginRight = '8px';
        btn.style.marginBottom = '8px';

        panel = document.createElement('div');
        panel.id = 'toloka-fill-panel';
        panel.style.display = 'none';
        panel.style.background = '#f5f5f5';
        panel.style.border = '1px solid #ccc';
        panel.style.borderRadius = '6px';
        panel.style.padding = '12px';
        panel.style.marginBottom = '12px';
        panel.style.maxWidth = '600px';

        const selectFolderBtn = document.createElement('button');
        selectFolderBtn.type = 'button';
        selectFolderBtn.textContent = 'Обрати файли';
        selectFolderBtn.className = 'mainoption';
        selectFolderBtn.style.marginRight = '8px';

        const dropZone = document.createElement('div');
        dropZone.style.border = '2px dashed #888';
        dropZone.style.borderRadius = '6px';
        dropZone.style.padding = '24px';
        dropZone.style.textAlign = 'center';
        dropZone.style.marginTop = '10px';
        dropZone.style.background = '#fff';
        dropZone.textContent = 'або перетягніть сюди meta.json (можна разом з mediainfo.txt)';

        const status = document.createElement('div');
        status.style.marginTop = '10px';
        status.style.minHeight = '20px';
        status.style.fontSize = '12px';
        status.style.color = '#666';

        const closeBtn = document.createElement('button');
        closeBtn.type = 'button';
        closeBtn.textContent = 'Закрити';
        closeBtn.style.marginLeft = '8px';

        const tmdbRow = document.createElement('div');
        tmdbRow.style.marginBottom = '10px';
        const tmdbLabel = document.createElement('label');
        tmdbLabel.textContent = 'TMDB API key (для української локалізації): ';
        const tmdbInput = document.createElement('input');
        tmdbInput.type = 'password';
        tmdbInput.placeholder = 'Збережено повторно використовується';
        tmdbInput.style.width = '220px';
        tmdbInput.style.marginRight = '6px';
        tmdbInput.value = getStoredTmdbKey();
        tmdbInput.autocomplete = 'off';
        const tmdbSave = document.createElement('button');
        tmdbSave.type = 'button';
        tmdbSave.textContent = 'Зберегти';
        tmdbSave.className = 'mainoption';
        tmdbSave.style.marginRight = '6px';
        const tmdbHint = document.createElement('span');
        tmdbHint.style.fontSize = '11px';
        tmdbHint.style.color = '#666';
        tmdbHint.textContent = getStoredTmdbKey() ? ' (ключ збережено)' : '';
        tmdbSave.addEventListener('click', () => {
            const v = tmdbInput.value.trim();
            setStoredTmdbKey(v);
            tmdbHint.textContent = v ? ' (ключ збережено)' : ' (ключ видалено)';
        });
        tmdbRow.appendChild(tmdbLabel);
        tmdbRow.appendChild(tmdbInput);
        tmdbRow.appendChild(tmdbSave);
        tmdbRow.appendChild(tmdbHint);

        panel.appendChild(tmdbRow);
        panel.appendChild(selectFolderBtn);
        panel.appendChild(closeBtn);
        panel.appendChild(document.createElement('br'));
        panel.appendChild(dropZone);
        panel.appendChild(status);

        function setStatus(msg, isError) {
            status.textContent = msg;
            status.style.color = isError ? '#c00' : '#666';
        }

        function tryFillWithMeta(meta, notices) {
            try {
                populateForm(form, meta);
                let msg = 'Форму заповнено.';
                if (notices && notices.length) {
                    msg += ' Увага: ' + notices.join('; ') + '.';
                    setStatus(msg, false);
                    status.style.color = '#996600';
                } else {
                    setStatus(msg, false);
                }
                const linksContainer = getLinksPanel();
                if (linksContainer) {
                    const initial = getInitialLinks(meta);
                    renderLinksPanel(linksContainer, initial);
                    resolveExtraLinks(initial).then(resolved => {
                        renderLinksPanel(linksContainer, resolved);
                    }).catch(() => { });
                }
            } catch (e) {
                setStatus('Помилка: ' + e.message, true);
            }
        }

        function readTextFile(file) {
            return new Promise((resolve, reject) => {
                const r = new FileReader();
                r.onload = () => resolve(r.result);
                r.onerror = () => reject(new Error('Failed to read file ' + file.name));
                r.readAsText(file, 'UTF-8');
            });
        }

        async function handleFiles(files) {
            const fileList = Array.from(files);
            const metaFile = fileList.find(f => f.name === 'meta.json');

            if (!metaFile) {
                setStatus('Не знайдено meta.json у вибраних файлах.', true);
                return;
            }

            setStatus('Читаю файли…');
            try {
                // Read meta.json
                const metaText = await readTextFile(metaFile);
                let meta;
                try {
                    meta = JSON.parse(metaText);
                } catch (e) {
                    throw new Error('Помилка парсингу meta.json: ' + e.message);
                }

                // Check for mediainfo.txt (various names)
                const mediaInfoFile = fileList.find(f => {
                    const n = f.name.toLowerCase();
                    return n === 'mediainfo.txt' || n === 'mediainfo_cleanpath.txt';
                });
                if (mediaInfoFile) {
                    try {
                        const infoText = await readTextFile(mediaInfoFile);
                        if (infoText) meta.mediainfo_raw = infoText;
                    } catch (e) {
                        console.warn('Failed to read mediainfo file', e);
                    }
                }

                // Continue with processing
                const apiKey = (tmdbInput.value || getStoredTmdbKey() || '').trim();
                const notices = [];
                if (!apiKey && metaNeedsTmdb(meta)) {
                    notices.push('немає TMDB ключа — опис і жанри можуть бути не українською');
                }
                if (apiKey && metaNeedsTmdb(meta)) {
                    setStatus('Отримую дані TMDB (українською)…');
                    try {
                        const tmdbData = await fetchTmdbData(apiKey, meta, { formHint: getFormType() });
                        if (tmdbData) {
                            meta._tmdb = tmdbData;
                            notices.push(...tmdbUkrainianWarnings(tmdbData));
                        }
                    } catch (e) {
                        notices.push('TMDB: ' + e.message);
                    }
                }
                tryFillWithMeta(meta, notices);

            } catch (e) {
                setStatus('Помилка: ' + e.message, true);
            }
        }

        function openFilesDialog() {
            const input = document.createElement('input');
            input.type = 'file';
            input.multiple = true;
            input.accept = '.json,.txt';
            input.onchange = () => {
                if (input.files && input.files.length) {
                    handleFiles(input.files);
                }
            };
            input.click();
        }

        selectFolderBtn.addEventListener('click', openFilesDialog);
        closeBtn.addEventListener('click', () => { panel.style.display = 'none'; });

        dropZone.addEventListener('dragover', (e) => { e.preventDefault(); e.stopPropagation(); dropZone.style.background = '#e8f4fc'; });
        dropZone.addEventListener('dragleave', () => { dropZone.style.background = '#fff'; });
        dropZone.addEventListener('drop', (e) => {
            e.preventDefault();
            e.stopPropagation();
            dropZone.style.background = '#fff';

            const dt = e.dataTransfer;
            if (dt && dt.files && dt.files.length) {
                handleFiles(dt.files);
            } else {
                setStatus('Перетягніть файли.', true);
            }
        });

        btn.addEventListener('click', () => {
            panel.style.display = panel.style.display === 'none' ? 'block' : 'none';
            if (panel.style.display === 'block') setStatus('');
        });

        const linksCol = document.createElement('div');
        linksCol.id = LINKS_PANEL_ID;
        linksCol.style.flex = '0 0 auto';
        linksCol.style.minWidth = '200px';
        linksCol.style.background = '#f9f9f9';
        linksCol.style.border = '1px solid #ddd';
        linksCol.style.borderRadius = '6px';
        linksCol.style.padding = '12px';
        linksCol.style.fontSize = '13px';

        const rowFlex = document.createElement('div');
        rowFlex.style.display = 'flex';
        rowFlex.style.gap = '20px';
        rowFlex.style.alignItems = 'flex-start';
        const leftBox = document.createElement('div');
        leftBox.appendChild(btn);
        leftBox.appendChild(panel);
        rowFlex.appendChild(leftBox);
        rowFlex.appendChild(linksCol);

        const wrap = document.createElement('tr');
        wrap.innerHTML = '<td class="row2" colspan="2" style="padding:10px"></td>';
        wrap.querySelector('td').appendChild(rowFlex);
        table.tBodies[0].insertBefore(wrap, firstRow);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', injectUI);
    } else {
        injectUI();
    }
})();
